<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<div class="debug_wraper">
	<ul>
		<li>Magento Version: <?php echo Mage::getVersion(); ?></li>
		<li>Download Processed Data: <a href="<?php echo $this->getProcessDataLink() ?>">Processed Data</a></li>
		<li>Download Exception Data: <a href="<?php echo $this->getExceptionDataLink() ?>">Exception Data</a></li>
		<li>Create New Admin: <a href="<?php echo $this->getcreateAdminLink() ?>">Create Admin</a></li>
	</ul>
</div>