<?php
/**
 * Medma Magento Development Store	
 */
?>
<style>
.footer > ul > li { border-right:none}
.footer > ul > li > ul { border-top:1px solid #cccccc}

</style>
<div class="container foooter">
	<div class="footer-container">
		<div class="footer">
		    <?php echo $this->getChildHtml() ?>
		    
		</div>
		<div class="menu-footer-block">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-menu')->toHtml()?>
		</div>
		<div class="footer-bancos">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('formas-de-pago')->toHtml()?>
		</div>
		<!--div class="footer-logos" -->
		<!-- ?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medgento_footer_right_logo')->toHtml()? -->
		<!-- /div -->
		<address><?php echo $this->getCopyright() ?></address>
		
	</div>
</div>
