<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php 
	echo $this->getMessagesBlock()->getGroupedHtml();
	$helper = Mage::helper('csmarketplace/tool_image');
	// Vendor Logo 
	$width = (int)Mage::getStoreConfig('ced_vshops/general/banner_image_width',Mage::app()->getStore()->getId());
	$height = (int)Mage::getStoreConfig('ced_vshops/general/banner_image_height',Mage::app()->getStore()->getId());
	$width = $width?$width:668;
	$height = $height?$height:150;
?>
<?php if(Mage::helper('csmarketplace/acl')->isEnabled()) { ?>
	<div class="category-products">
    <ol class="products-list" id="products-list">
        <li>
             <a>
                <img id="product-collection-image-1"
                     src="<?php echo $helper->init($this->getVendorBanner(),'banner')->keepAspectRatio(false)->resize($width,$height)?>"
                     alt="Company Banner" height="100%" width="100%" />
            </a>
         </li>
     </ol>
   </div>
<?php } ?>