<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

 $product= $this->getProduct();
 $vproduct = Mage::getModel("csmarketplace/vproducts");
 $vendorid = (int) $vproduct->getVendorIdByProduct($product);
 if($vendorid>0){
 	$vendors=Mage::getModel('csvendorvacation/vacation')->getCollection()->addFieldToFilter('vendor_id',$vendorid)->getData();
     $vendor=$vendors[0];
 } 	
 ?>
<span class="info_vacation">
<?php 
if($vendor['status']=='0'){
echo $vendor['vendormsg'];
}?>
</span>