<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php 
	$_element = $this->getElement();
	$_trId    = $_element->getHtmlContainerId();

?>
<?php if($_element->getNoSpan() !== true): ?>
<div<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?> class="wide form-group">
<?php endif; ?>
<?php echo $this->helper('csmarketplace')->__(strip_tags($_element->getLabel())); ?>
<div class="input-box">
	<?php echo $_element->getElementHtml() ?>
</div>
<?php if($_element->getNoSpan() !== true): ?>
</div>
<?php endif; ?>
