<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
 
?>
<?php $_order = $this->getOrder() ?>
<?php 
	$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
	$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
	<div class="panel panel-default for_print_order_button">
		<div class="panel-heading panel-head col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
		<div class="order_title">
    <?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?>
    <?php echo $this->getChildHtml('buttons') ?>
		</div>
		</div>
	 	<div class="panel-body">
		<div class="col-md-12">
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<div class="order-info-wrap">

<div class="order-info col-md-12">
		<h3 style="color:#23527C;"><?php echo  Mage::helper('sales')->__('Order Information') ?></h3>
</div>
<div class="col2-set order-info-box col-md-12" >
            <table width="100%" cellspacing="0" class="form-list">
            <tr>
                <td ><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                <td class="value"><strong><?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'long') ?></strong></td>
            </tr>
            <?php if ($orderAdminDate != $orderStoreDate):?>
            <tr>
                <td ><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                <td class="value"><strong><?php echo $orderStoreDate ?></strong></td>
            </tr>
            <?php endif;?>
            <tr>
                <td ><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                <td class="value"><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
            </tr>
            <tr>
                <td ><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                <td class="value"><strong><?php echo $this->getOrderStoreName() ?></strong></td>
            </tr>
           
            <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
            <tr>
                <td ><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td class="value"><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
            <tr>
                <td ><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td class="value"><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
		<div style="clear:both"></div>
	</div>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box col-md-12">
    <div class="col-1 col-md-6 order-info-box_custom order-info-box_billing space-adjust_left">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Shipping Address') ?></h4>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2 col-md-6 order-info-box_custom order-info-box_billing space-adjust_right">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Shipping Method') ?></h4>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box order-info-box_custom_wrap col-md-12" style="">
    <div class="col-1 col-md-6 order-info-box_custom order-info-box_billing space-adjust_left">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Billing Address') ?></h4>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2 col-md-6 order-info-box_custom order-info-box_payment space-adjust_right">
        <div class="box box-payment">
            <div class="box-title">
                <h4><?php echo $this->__('Payment Method') ?></h4>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
    <div style="clear:both;"></div>
</div>

