<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php $_order = $this->getOrder() ?>
  <div class="order-items order-details table-responsive">
		<table id="my-products-table" class="data-table table table-bordered table-hover table-striped">
        <col width="1"/>
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th class="head"><?php echo $this->helper('sales')->__('Product') ?></th>
                <th class="head"><span class="nobr"><?php echo $this->helper('sales')->__('Original Price') ?></span></th>
                <th class="head"><?php echo $this->helper('sales')->__('Price') ?></th>
                <th class="a-center head"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th class="head"><?php echo $this->helper('sales')->__('Subtotal') ?></th>
                <th class="head"><span class="nobr"><?php echo $this->helper('sales')->__('Tax Amount') ?></span></th>
                <th class="head"><span class="nobr"><?php echo $this->helper('sales')->__('Discount Amount') ?></span></th>
                <th class="last head"><span class="nobr"><?php echo $this->helper('sales')->__('Row Total') ?></span></th>
            </tr>
        </thead>
        <tfoot>
       	<?php echo $this->getChildHtml('order_totals') ?>
       	<?php echo $this->getChildHtml('earn') ?>
       </tfoot>
         <?php 		
		$vorder = Mage::registry('current_vorder');
		$_items = Mage::getModel('csmarketplace/vorders')->load($vorder->getId())->getItemsCollection(); ?>
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
</table>
  </div>