<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php $_element = $this->getElement() ?>
<?php if($_element->getNoSpan() !== true): ?>
<li class="wide">
<?php endif; ?>
<?php echo $_element->getLabelHtml() ?>
<div class="input-box">
	<?php echo $_element->getElementHtml() ?>
</div>
<?php if($_element->getNoSpan() !== true): ?>
</li>
<?php endif; ?>
