<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php  $_order = $this->getOrder();
$vorder = Mage::registry('current_vorder');
?>
<?php 
if($this->getRequest()->getActionName()!="print"){?>
<button style="line-height: 1.2em;float:right" type="button" onclick="window.open('<?php echo $this->getPrintUrl($vorder); ?>')" title="<?php echo $this->__('Print Order') ?>" class="button btn btn-warning uptransform"><span><span><?php echo $this->__('Print Order') ?></span></span></button>

<?php }?>
<?php echo $this->getChildHtml(); ?>
