<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php
$vorder = Mage::registry('current_vorder');
$_order  = $this->getOrder();
$_source = $this->getSource();
$_fullInfo  = $this->getFullTaxInfo();
?>

<tr class="0">
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <div class="summary-collapse">
        <strong>
            <?php echo  $this->helper('csmarketplace')->__('Grand Total (Earned)')?>
        </strong>
        </div>
    </td>
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
    	<strong>
        <?php echo  Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getOrderTotal()); ?>
         </strong>
    </td>
</tr>
<tr class="0">
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <div class="summary-collapse">
        	<strong>
            <?php echo  $this->helper('csmarketplace')->__('Commission Fee')?>
        </div>
    </td>
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
    	<strong>
        <?php echo Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getShopCommissionFee()); ?>
         </strong>
    </td>
</tr>
<tr class="0">
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <div class="summary-collapse">
        	<strong>
            <?php echo  $this->helper('csmarketplace')->__('Net Earned')?>
             </strong>
        </div> 
    </td>
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
    	<strong>
        <?php echo Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getOrderTotal()-$vorder->getShopCommissionFee()); ?>
         </strong>
    </td>
</tr>
