<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php
$vorder = Mage::registry('current_vorder');
$_order  = $this->getOrder();
$_source = $this->getSource();
$_fullInfo  = $this->getFullTaxInfo();
?>
<?php if($vorder->getBaseTaxAmount()){?>
<tr class="0">
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <div class="summary-collapse">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <?php echo Mage::helper('sales')->__('Total Tax') ?>
        <?php else: ?>
            <?php echo Mage::helper('sales')->__('Tax') ?>
        <?php endif;?>
        </div>
    </td>
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <?php echo $this->displayAmount($vorder->getPurchaseTaxAmount(), $vorder->getBaseTaxAmount()); ?>
    </td>
    <?php }?>
</tr>
