<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php
	$vdebugpage = $this->getVdebugpage();
	$resource = Mage::getSingleton('core/resource');
	$readConnection = $resource->getConnection('core_read');
	
	$mysqlVersion =  $readConnection->fetchOne('SELECT VERSION()');
	$mysqlVersion    = $mysqlVersion ? $mysqlVersion : 'undefined';
       $match = array();
       if (preg_match("#^([0-9\.]+)#", $mysqlVersion, $match)) {
           $mysqlVersion = $match[0];
       }
?>
<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;" summary="<?php echo $this->__('Magento Platform Info') ?>">
    <tbody  bgcolor="#F6F6F6">
		<tr>
			<td>Current PHP version</td>
			<td><?php echo  phpversion(); ?></td>
		</tr>
		<tr>
			<td>Mysql Version</td>
			<td><?php echo $mysqlVersion; ?></td>
		</tr>
		<tr>
			<td>Magento Version</td>
			<td><?php echo Mage::getVersion(); ?></td>
		</tr>
		<tr>
			<td>Csmarketplace Version</td>
			<td><?php echo Mage::getConfig()->getModuleConfig("Ced_CsMarketplace")->version; ?></td>
		</tr>
		<tr>
			<td>Site Url</td>
			<td><?php echo Mage::getBaseUrl(); ?></td>
		</tr>
		<tr>
			<td>Module</td>
			<td><?php echo $vdebugpage['module']; ?></td>
		</tr>
		<tr>
			<td>Router</td>
			<td><?php echo $vdebugpage['router']; ?></td>
		</tr>
		<tr>
			<td>Controller</td>
			<td><?php echo $vdebugpage['controller']; ?></td>
		</tr>
		<tr>
			<td>Action</td>
			<td><?php echo $vdebugpage['action']; ?></td>
		</tr>
   	</tbody>
</table>
