<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php 
$products=$this->getProducts();
	?>
<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;" summary="<?php echo $this->__('Products') ?>">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Product Name') ?></th>
            <th  align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('SKU') ?></th>
        </tr>
    </thead>
    <tbody bgcolor="#F6F6F6">
    <?php $i=0;?>
        <?php foreach ($products[1] as $key=>$product): ?>

            <tr  align="left" 
				style="font-size: 13px; padding: 3px 9px" <?php echo $i%2 ? ' bgcolor="#EAEAEA"' : '#F6F6F6' ?> class="border">
                <td class="number"><?php echo $product->getName();?></td>
                <td class="number"><?php echo $product->getSku();?></td>
            </tr>
            <?php $i++;?>
        <?php endforeach; ?>
   	</tbody>
</table>
