<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php  $products = $this->getProducts();
	?>
<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;" summary="<?php echo $this->__('Products') ?>">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Product Name') ?></th>
            <th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('SKU') ?></th>
            <th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Qty') ?></th>
            <th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Website(s)') ?></th>
        </tr>
    </thead>
    <tbody  bgcolor="#F6F6F6">
    <?php $i=0;?>
        <?php foreach ($products[0] as $product): ?>
            <tr align="left" 
				style="font-size: 13px; padding: 3px 9px" <?php echo $i%2 ? ' bgcolor="#EAEAEA"' : '#F6F6F6' ?> class="border">
                <td class="number">
                <?php if($products[1][$product->getId()]->getCheckStatus()==Ced_CsMarketplace_Model_Vproducts::APPROVED_STATUS && $product->getStatus()==Mage_Catalog_Model_Product_Status::STATUS_ENABLED){?>
                <a href="<?php echo $product->getProductUrl() ?>" title="<?php  echo $product->getName()?>" ><?php echo $product->getName();?></a>
                <?php }else{?>
                <?php echo $product->getName();?>
                <?php }?>
                </td>
                <td class="number"><?php echo $product->getSku();?></td>
                <td class="number"><?php echo $product->getStockItem()->getQty();?></td>
                <td class="number">
                <?php 
                $WebsiteName=array();
                	foreach($product->getWebsiteIds() as $websiteId){
                		if($websiteId!=0)
                			$WebsiteName[]=Mage::getModel('core/website')->load($websiteId)->getName();
                	} 
                	echo implode(',',$WebsiteName);    	
                ?>
                
                </td>
            </tr>
            <?php $i++;?>
        <?php endforeach; ?>
   	</tbody>
</table>
