<?php
/**
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
		<div class="input-group">
		    <?php if(!$_product->isGrouped()): ?>
		    <label class="input-group-addon" for="qty"><?php echo $this->__('Qty:') ?></label>
		    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty form-control" />
		    <?php endif; ?>
			<span class="input-group-btn">
				<button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-default btn-cart" onclick="productAddToCartForm.submit(this)">
					<span><span><?php echo $buttonTitle ?></span></span>
				</button>
			</span>
		</div>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
