<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php  $_order = $this->getOrder();?>
<?php $currentVendor = $this->getVendor();?>
<table cellspacing="0" cellpadding="0" border="0" width="650"
	style="border: 1px solid #EAEAEA;"
	summary="<?php echo $this->__('Items Ordered') ?>">
	<col />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<thead>
		<tr>
			<th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Product Name') ?></th>
			<th align="left" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('SKU') ?></th>
			<th align="center" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Qty') ?></th>
			<th align="right" bgcolor="#EAEAEA"
				style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Subtotal') ?></th>
		</tr>

	</thead>
   
      <?php $i=0; foreach ($_order->getAllItems() as $_item): ?>
       <?php if($_item->getVendorId() != $currentVendor->getId()) continue;?>
    <?php if($_item->getParentItem()) continue; else $i++; ?>
    <tbody <?php echo $i%2 ? ' bgcolor="#F6F6F6"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tbody>
        <?php echo $this->getChildHtml('vendor_order_totals') ?>
        <?php echo $this->getChildHtml('earn') ?>
    </tbody>
</table>
    