<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
    <?php $_totals = $this->getTotals('')?>
    <?php if ($_totals):?>
    <?php foreach ($_totals as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?php echo $_code?>">
            <td <?php echo $this->getLabelProperties()?> class="a-right" colspan="3">
                <?php if ($_total->getStrong()):?>
                <?php echo $_total->getLabel()?>
                <?php else:?>
                <?php echo $_total->getLabel()?>
                <?php endif?>
            </td>
            <?php if ($_total->getStrong()):?>
            <td <?php echo $this->getValueProperties()?> class=" a-right emph">
                <?php echo $this->formatValue($_total) ?>
            <?php else:?>
            <td class="a-right" <?php echo $this->getValueProperties()?>>
                <?php echo $this->formatValue($_total) ?>
            <?php endif?>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    
    <?php endif?>

    <?php $_totals = $this->getTotals('footer')?>
    <?php if ($_totals):?>
    <?php foreach ($this->getTotals('footer') as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?php echo $_code?>">
            <td <?php echo $this->getLabelProperties()?> class="a-right" colspan="3">
                <?php echo $_total->getLabel()?>
            </td>
            <td <?php echo $this->getValueProperties()?> class="a-right">
                <?php echo $this->formatValue($_total) ?>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    <?php endif?>
