<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
 <?php $helper = Mage::helper ( 'csmarketplace' ); ?>
  <div class="page-title">
        <h1><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $helper->__('Orders Report') ?>      
         <button style="line-height: 1.2em;float:right" type="button" onclick="window.location='<?php echo $this->getUrl('*/*/vproducts'); ?>'" title="<?php echo $helper->__('View')." ".$helper->__('Products Report') ?>" class="button"><span><span><?php echo $helper->__('View')." ".$helper->__('Products Report') ?></span></span></button>
        </h1>
        <div style="clear:both"></div>
   </div>
<div>
 <?php echo $this->getChildHtml('vorders_reports_filter') ?>
</div>
<br/>
<div>
 <?php echo $this->getChildHtml('vorders_reports_list') ?>
</div>