<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
 
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getVpayments(); 
$params = Mage::getSingleton('core/session')->getData('payment_filter');

?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
			<div  style="line-height:31px;font-size:17px;display:inline;text-transform: uppercase;">
			<?php echo $this->__('Transactions List') ?>
			</div>
         </div>
 	<div class="panel-body">
 	<div class="col-md-12" style="margin-top:10px;">
<form id="payment_form"
	action=""
	enctype="multipart/form-data" method="post">
	<div class="vendor-button-set buttons-set filter_button">
	<?php if(count($collection)>0){ ?>
		<div class="col-md-4 export-button" style="padding-left:0;">
			<button onClick="window.location='<?php echo $this->getUrl('*/*/exportCsv',array('_secure'=>true,'_nosid'=>true)); ?>'" class="uptransform btn btn-warning button" title="Export Orders" style="margin:2px; float:left;">
						<span><span><?php echo $this->__('Export') ?></span></span>
			</button>
		</div>
		<div class="col-md-8 filter-buttons" style="margin-left:0;padding-right:0;text-align:right;">
	<?php }
	else{ 
		 ?>
		<div class="col-md-12" style="margin-left:0;padding-right:0;margin-bottom:5px;text-align:right;">
	<?php }?>
		<button  style="margin:2px" onClick="filterPayment(0);" class="button btn btn-info uptransform " title="<?php echo $this->__('Filter') ?>" type="submit" id="Filter"	>
			<span><span><?php echo $this->__('Filter') ?></span></span>
		</button> 
		<button  style="margin:2px" onClick="filterPayment(1);" class="button btn btn-info uptransform" title="<?php echo $this->__('Reset Filter') ?>" type="button" id="Filter"	>
			<span><span><?php echo $this->__('Reset Filter') ?></span></span>
		</button>
		</div>
		
	</div>	
	



<div style="clear:both;"></div>
<br/>
<?php echo $this->getPagerHtml(); ?>
<div style="clear:both"></div>
<div class="order-items order-details table-responsive">
		<table id="my-products-table" class="table table-bordered table-hover table-striped">
	    <col width="2" />
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1" />
	    <col width="1" />
	    <col width="1" />
		<thead>
			<tr style="background-color: #f5f5f5;">
				<th class="head"><?php echo $this->__('Created At #') ?></th>
				<th class="head"><?php echo $this->__('Payment Mode') ?></th>
				<th class="head"><?php echo $this->__('Transaction Id') ?></th>
				<th class="head"><?php echo $this->__('Amount') ?></th>
				<th class="head"><?php echo $this->__('Adjustment')." " ?><?php echo $this->__('Amount') ?></th>
				<th class="head"><?php echo $this->__('Net Amount') ?></th>
				<th class="head"><?php echo $this->__('Action') ?></th>
			</tr>
         	<tr class="filter">
				<th class="filter">
					<div class="list_filter">
					<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle" id="date_from_trig" />
					<input type="text" id="created_at_from" name="created_at[from]" class="form-control" value="<?php echo (isset($params['created_at']['from']) && urldecode($params['created_at']['from'])!="")?urldecode($params['created_at']['from']):""; ?>" /></div>
					<div class="list_filter">
					<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle" id="date_to_trig" />
					<input type="text"  id="created_at_to" name="created_at[to]"  class="form-control" value="<?php echo (isset($params['created_at']['to']) && urldecode($params['created_at']['to'])!="")?urldecode($params['created_at']['to']):""; ?>"  /></div>
				</th>
	        	<th class="filter">
					<div class="list_filter"><input type="text" name="payment_method"  class="form-control filter" value="<?php echo (isset($params['payment_method']) && urldecode($params['payment_method'])!="")?urldecode($params['payment_method']):""; ?>" /></div>
				</th>
	            <th class="filter">
					<div class="list_filter"><input  type="text"  onUnfocus="filterPayment(0);" class="form-control filter" name="transaction_id"  value="<?php echo (isset($params['transaction_id']) && urldecode($params['transaction_id'])!="")?urldecode($params['transaction_id']):""; ?>"  /></div>
				</th> 
	            <th class="filter">
					<div class="list_filter"><input type="text" name="amount[from]" class="form-control filter"  value="<?php echo (isset($params['amount']['from']) && urldecode($params['amount']['from'])!="")?urldecode($params['amount']['from']):""; ?>" /></div>
					<div class="list_filter"><input type="text" name="amount[to]" class="form-control filter" value="<?php echo (isset($params['amount']['to']) && urldecode($params['amount']['to'])!="")?urldecode($params['amount']['to']):""; ?>"  /></div>
				</th>
				<th class="filter"><div></div>
					<div class="list_filter"><input type="text" name="fee[from]" class="form-control filter" value="<?php echo (isset($params['fee']['from']) && urldecode($params['fee']['from'])!="")?urldecode($params['fee']['from']):""; ?>"  /></div>
					<div class="list_filter"><input type="text" name="fee[to]"  class="form-control filter"  value="<?php echo (isset($params['fee']['to']) && urldecode($params['fee']['to'])!="")?urldecode($params['fee']['to']):""; ?>"  /></div>
				</th>
				<th class="filter">
					<div class="list_filter"><input type="text" name="net_amount[from]" class="form-control filter" value="<?php echo (isset($params['net_amount']['from']) && urldecode($params['net_amount']['from'])!="")?urldecode($params['net_amount']['from']):""; ?>"  /></div>
					<div class="list_filter"><input type="text" name="net_amount[to]" class="form-control filter" value="<?php echo (isset($params['net_amount']['to']) && urldecode($params['net_amount']['to'])!="")?urldecode($params['net_amount']['to']):""; ?>"  /></div>
				</th>
	            <th class="filter"></th>
			</tr>
	    </thead>
	    <tbody>
		<?php if(count($collection)>0): ?>
	        <?php $_odd = ''; ?>
	        <?php foreach ($collection as $_payment): ?>
	        <tr>
	            <td class="status"><?php echo  Mage::helper('core')->formatDate( $_payment->getCreatedAt() , 'medium', true);	 ?></td>
	            <td class="status"><?php echo Mage::helper('csmarketplace/acl')->getDefaultPaymentTypeLabel($_payment->getPaymentMethod()); ?></td>
				<td class="number"><?php echo $_payment->getTransactionId() ?></td>     
	            <td class="date"><?php echo Mage::app()->getLocale()->currency($_payment->getCurrency())->toCurrency($_payment->getAmount());  ?></td>
				<td class="date"><?php echo Mage::app()->getLocale()->currency($_payment->getCurrency())->toCurrency($_payment->getFee());  ?></td>
				<td class="number"><?php echo Mage::app()->getLocale()->currency($_payment->getCurrency())->toCurrency($_payment->getNetAmount());  ?></td>
	     		 <td class="a-center view number">
	                <span class="number"><a class="btn btn-info btn-outline btn-circle" title="<?php echo $this->__('View') ?>" href="<?php echo $this->getViewUrl($_payment) ?>"><i style="font-size:15px;" class="fa fa-info"></i></a>
	                </span>
	            </td>
	        </tr>
	        <?php endforeach; ?>
	    
				<?php else: ?>
				<tr><td colspan="7">
				<div>
				<p><?php echo $this->__('No Transactions Available'); ?></p>
				</div>
		</td></tr>		
			<?php endif ?>
		</tbody>
	</table>
</div>
<?php echo $this->getPagerHtml(); ?>
  </form>
  </div>
  </div>
  </div>
  </div>
  </div>
<script type="text/javascript">decorateTable('my-payments-table');</script>




<style>
.list_filter input{
width:100%;
padding: 2px;
}
#date_from_trig, #date_to_trig{
float:left;
}
#created_at_from, #created_at_to{
width:78%;
}
</style>
<script type="text/javascript">// <![CDATA[
setTimeout(function(){
Calendar.setup({
    inputField : 'created_at_from',
    ifFormat : '%m/%e/%y',
    button : 'date_from_trig',
    align : 'Bl',
    singleClick : true
});

Calendar.setup({
    inputField : 'created_at_to',
    ifFormat : '%m/%e/%y',
    button : 'date_to_trig',
    align : 'Bl',
    singleClick : true
});
}, 500);
// ]]></script>

<script type="text/javascript">

<?php if($this->getRequest()->getActionName()=='index'){ ?>
	filterPayment(2);
  <?php } ?>
  
	jced(document).ready(function(){
	  jced("#payment_form").submit(function() {
				return false;
			});
	});


function filterPayment(reset){
		var params ;
		if(reset==2)
        	reset=0;
    	jced('#activity-loading').show();
		if(reset==1)
			params ='{reset_filter:1}';
		else
			params = jced("#payment_form").serialize().replace('+','%20');

		new Ajax.Request("<?php 
		$urlParams['_nosid'] = true;
		if(Mage::app()->getStore()->isCurrentlySecure()){
			$urlParams['_secure'] = true;
		}	
		echo   $this->getUrl('csmarketplace/vpayments/filter',$urlParams) ?>", {
           method: 'Post',
           parameters:params,
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
               jced('#activity-loading').hide();

           }
       });
   }
   
   
   function setLocation(url){
	   jced('#activity-loading').show();
		new Ajax.Request(url, {
           method: 'Get',
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
               jced('#activity-loading').hide();
           }
       });
   }
   
   jced('.pages a').click(function(e){	
		var url = jced(this).attr('href');
		if(url!="#"){
			jced('#activity-loading').show();
			e.preventDefault();
			new Ajax.Request(url, {
	           method: 'Get',
	           onComplete: function(transport) {
	               jced('.vendor-dashboard').html(transport.responseText);
	               jced('#activity-loading').hide();
	           }
	       });
		}
	});
 
</script>