<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php if ($_item = $this->getItem()): ?>
        <span class="nobr">
        <?php if ($_item->getQtyOrdered() > 0): ?>
            <?php echo $this->__('Ordered'); ?>: <strong><?php echo $_item->getQtyOrdered()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($_item->getQtyInvoiced() > 0): ?>
            <?php echo $this->__('Invoiced'); ?>: <strong><?php echo $_item->getQtyInvoiced()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($_item->getQtyShipped() > 0): ?>
            <?php echo $this->__('Shipped'); ?>: <strong><?php echo $_item->getQtyShipped()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($_item->getQtyCanceled() > 0): ?>
            <?php echo $this->__('Canceled'); ?>: <strong><?php echo $_item->getQtyCanceled()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($_item->getQtyRefunded() > 0): ?>
            <?php echo $this->__('Refunded'); ?>: <strong><?php echo $_item->getQtyRefunded()*1 ?></strong><br />
        <?php endif; ?>
        </span>
<?php endif; ?>
