<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
 
?>
<?php $_products = $this->getVproducts();
$helper = Mage::helper ( 'csmarketplace' );
$checkstatusarray=Mage::getModel('csmarketplace/vproducts')->getOptionArray();
$types = Mage::getModel('csmarketplace/system_config_source_vproducts_type')->toOptionArray(false,true);
$params = Mage::getSingleton('core/session')->getData('product_filter');
?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
			<div  style="line-height:31px;font-size:17px;display:inline;">
			<?php echo $helper->__('Products List') ?>
			</div>
			<div class="buttons-set" style="text-align:right;display:inline;">		
		                    <button class="btn btn-primary uptransform" style="line-height: 1.2em;float:right;" type="button" onclick="window.location='<?php echo $this->getUrl('*/*/new',array('_secure'=>true,'_nosid'=>true)); ?>'" title="<?php echo $helper->__('New')." ".$helper->__('Product') ?>" class="button">
								<span>
									<span><?php echo $helper->__('New')." ".$helper->__('Product') ?></span>
								</span>
							</button>
	         </div>
         </div>
 	<div class="panel-body">
	<div class="col-md-12">
	<form action="" enctype="multipart/form-data" method="post" id="product-list-form">
		<br/>
		<label for="store_switcher"><?php echo $this->__('Choose Store View') ?>:</label>
		<div style="clear:both"></div>
		<div>
		<div class="col-md-9" style="padding-left:0;">
		<?php echo $this->getLayout()->createBlock('csmarketplace/vproducts_store_switcher')->setSwitchUrl($this->getUrl('*/*/*', array('_secure'=>true,'_current'=>false, '_query'=>false,'_nosid'=>true)))->toHtml();?>
		</div>
		<div class="filter_button col-md-3" style="margin-left:0;padding-right:0;text-align:right;">	
			<button  onclick="filterProducts(0);" class="button btn btn-info uptransform" title="<?php echo $helper->__('Filter') ?>" type="submit" id="Filter"	>
					<span><span><?php echo $helper->__('Filter') ?></span></span>
			</button>
			<button  onclick="filterProducts(1);" class="button btn btn-info uptransform" title="<?php echo $helper->__('Reset Filter') ?>" type="button" id="Filter"	>
						<span><span><?php echo $helper->__('Reset Filter') ?></span></span>
			</button>
		</div>
		<div style="clear:both"></div>	
		</div>
	<?php echo $this->getPagerHtml(); ?>
	<div style="clear:both"></div>	
	<div class="order-items order-details table-responsive">
		<table id="my-products-table" class="table table-bordered table-hover table-striped">
		    <col width="1"/>
		    <col width="1"/>
		   	<col width="1"/>
		    <col width="1"/>
		    <col width="1"/>
		    <col width="1"/>
		    <col width="1"/>
		    <col width="1"/>
		    <thead>
		    <tr style="background-color: #f5f5f5;">
				<th class="head"><?php echo $helper->__('ID') ?></th>
				<th class="head"><?php echo $helper->__('Product') ?></th>
				<th class="head"><?php echo $helper->__('Product Name') ?></th>
				<th class="head"><?php echo $helper->__('Product')." " ?><?php echo $helper->__('Type') ?></th>
				<th class="head"><?php echo $helper->__('Status') ?></th>
				<th class="head"><?php echo $helper->__('Price') ?></th>
				<th class="head"><?php echo $helper->__('Qty') ?></th>
				<th class="head"><?php echo $helper->__('Action') ?></th>
			</tr>
         	<tr class="filter">
              	<th class="filter">
		        	<div class="product-list-filter">	
		        		<input type="text" name="entity_id[from]" class="input-text-tiny form-control filter" value="<?php echo (isset($params['entity_id']['from']) && urldecode($params['entity_id']['from'])!="")?urldecode($params['entity_id']['from']):""; ?>"/>
		        	</div>
		        	<div class="product-list-filter">	
		        		<input type="text" name="entity_id[to]"  class="input-text-tiny form-control filter" value="<?php echo (isset($params['entity_id']['to']) && urldecode($params['entity_id']['to'])!="")?urldecode($params['entity_id']['to']):""; ?>"/>
		        	</div>
		        </th>
		        
		        <th></th>
		        
		        <th class="filter">
		        	<div class="product-list-filter"><input type="text" name="name" class="input-text-smallmedium form-control filter" value="<?php echo (isset($params['name']) && urldecode($params['name'])!="")?urldecode($params['name']):""; ?>"/></div>
				</th> 
				
		        <th class="filter">
		           <div class="product-list-filter">
		           <select type="text" name="type_id" class="input-select-small form-control filter" value="">
		           <?php foreach($types as $type) { echo $type['label'];?>
								<?php if(!isset($type['value']) || !isset($type['label'])) continue; ?>
								<option <?php echo (isset($params['type_id']) && urldecode($params['type_id'])==$type['value'])?"selected":"";?> value="<?php echo $type['value']; ?>"><?php echo $helper->__($type['label']); ?></option>
							<?php } ?>
		            </select>
		            </div>
				</th>
				
		  		<th class="filter">
		            <div class="product-list-filter">
		            <select type="text" name="check_status" class="filter input-select-small product-list-checkstatus form-control" value="">
		            <option value=""></option>
		           <?php foreach($checkstatusarray as $key=>$val) { ?>
									<option <?php echo (isset($params['check_status']) && (urldecode($params['check_status'])!='')&&(urldecode($params['check_status'])==$key))?"selected":"";?> value="<?php echo $key; ?>"><?php echo $helper->__($val); ?></option>
								<?php } ?>
		            </select></div>
		            <div <?php if(isset($params['check_status']) && urldecode($params['check_status'])!=Ced_CsMarketplace_Model_Vproducts::APPROVED_STATUS) echo "style='display:none'"; else echo ""; ?> class="product-list-filter product-list-status">
		            <select type="text" name="status" class="filter input-select-small form-control" value="">
		          			<option value=""></option>
		          			<option <?php echo isset($params['status']) && urldecode($params['status'])==Mage_Catalog_Model_Product_Status::STATUS_ENABLED?"selected":"";?> value="<?php echo Mage_Catalog_Model_Product_Status::STATUS_ENABLED;?>"><?php echo $helper->__('Enabled')?></option>
		          			<option <?php echo isset($params['status']) && urldecode($params['status'])==Mage_Catalog_Model_Product_Status::STATUS_DISABLED?"selected":"";?> value="<?php echo Mage_Catalog_Model_Product_Status::STATUS_DISABLED?>"><?php echo $helper->__('Disabled')?></option>
		            </select></div>
		       	</th>
		       	
		      	<th class="filter">
		            <div class="product-list-filter">
		            	<input type="text" name="price[from]" id="price_from" class="filter input-text-tiny form-control" value="<?php echo (isset($params['price']['from']) && urldecode($params['price']['from'])!="")?urldecode($params['price']['from']):""; ?>"/>
		            </div>
		        	<div class="product-list-filter">
		        		<input type="text" id="price_to" name="price[to]" class="filter input-text-tiny form-control" value="<?php echo (isset($params['price']['to']) && urldecode($params['price']['to'])!="")?urldecode($params['price']['to']):""; ?>"/>
		        	</div>
		        </th>
		        
		       	<th class="filter">
		      		<div class="product-list-filter">
		           		<input type="text" name="qty[from]" class="input-text-tiny form-control filter" value="<?php echo (isset($params['qty']['from']) && urldecode($params['qty']['from'])!="")?urldecode($params['qty']['from']):""; ?>"/>
		           	</div>
		        	<div class="product-list-filter">
		        		<input type="text"  name="qty[to]" class="input-text-tiny form-control filter" value="<?php echo (isset($params['qty']['to']) && urldecode($params['qty']['to'])!="")?urldecode($params['qty']['to']):""; ?>"/>
		        	</div>
		  		</th>
		            
              	<th></th>
           	</tr>
      		</thead>
		    <tbody>
		    	<?php if(count($_products)>0): ?>
		        <?php $_odd = ''; ?>
		        <?php foreach ($_products as $_product): ?>
		        <?php
		        if($_products->getStoreId()==0 && Mage::app()->isSingleStoreMode())
		        	$productUrl=$_product->getProductUrl();
		        else if($_products->getStoreId()!=0)
		        	$productUrl=$_product->getUrlInStore(array('_store'=>$_products->getStoreId()));
		        
		        ?>
		        <tr>
		            <td class="date"><?php echo $_product->getId() ?></td>
		            
		            <td class="status">
			           	<?php if(($_product->getCheckStatus()==Ced_CsMarketplace_Model_Vproducts::APPROVED_STATUS) && (($_product->getStatus()==Mage_Catalog_Model_Product_Status::STATUS_ENABLED && $_products->getStoreId()!=0)||($_products->getStoreId()==0 && Mage::app()->isSingleStoreMode()))){?>
			            	<a target="_blank" href="<?php echo $productUrl ?>" target="_blank" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" class="product-image">
			            	<img  width="50" height="35" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail',$_product->getImage())->constrainOnly(true)->resize(50, 35); ?>"/>
			            	</a>
			            <?php }else {?>
			            <img  width="50" height="35" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail',$_product->getImage())->constrainOnly(true)->resize(50, 35); ?>"/>
			            <?php }?>
		            </td>
		            
		            <td class="status">
			            <?php if(($_product->getCheckStatus()==Ced_CsMarketplace_Model_Vproducts::APPROVED_STATUS) && (($_product->getStatus()==Mage_Catalog_Model_Product_Status::STATUS_ENABLED && $_products->getStoreId()!=0)||($_products->getStoreId()==0 && Mage::app()->isSingleStoreMode()))){?>
			            <a target="_blank" href="<?php echo $productUrl?>" target="_blank" title="<?php  echo $_product->getName()?>"><?php echo $_product->getName() ?></a>
			            <?php }else{?>
			            <?php echo $_product->getName(); 
						}
			            ?>
		            </td>    
		             
		            <td class="status"><?php echo $_product->getTypeId() ?></td>
		            
		            <td class="status"><?php echo $_product->getCheckStatus()?(($_product->getCheckStatus()==Ced_CsMarketplace_Model_Vproducts::APPROVED_STATUS)? "Approved":"Pending") : "Not Approved" ?>
		            <br/><?php if($_product->getCheckStatus()==Ced_CsMarketplace_Model_Vproducts::APPROVED_STATUS) echo $_product->getStatus()==Mage_Catalog_Model_Product_Status::STATUS_ENABLED?"(Enabled)":"(Disabled)"?>
		            </td>
		            
		            <td class="status"><?php echo  Mage::app()->getLocale()->currency(Mage::getModel('core/store')->load($_products->getStoreId())->getBaseCurrencyCode())->toCurrency($_product->getPrice())?></td>
		            
		            <td class="status"><?php echo round($_product->getQty());?></td>
		            
		     		<td class="a-center view number">
		                <span class="nobr number"><a title="<?php echo $this->__('Edit') ?>" class="btn btn-info  btn-outline btn-circle" href="<?php echo $this->getEditUrl($_product) ?>"><i class="fa fa-pencil"></i></a>
		                <a class="btn btn-danger  btn-outline btn-circle" title="<?php echo $helper->__('Delete') ?>" id="delete_product" href="#" onCLick="if(confirm('<?php echo $helper->__('Are you sure?') ?>'))window.location='<?php echo $this->getDeleteUrl($_product)?>'" class="link-reorder"><i class="fa fa-times"></i></a>
		                </span>
		            </td>
		        </tr>
		        <?php endforeach; ?>
		        <?php else: ?>
				<tr>
					<td colspan="8">
					<div>
					<p><?php echo $helper->__('No product records found'); ?></p>
					</div>
					</td>
				</tr>		
				<?php endif ?>
		    </tbody>
		</table>
	</div>
	<?php echo $this->getPagerHtml(); ?>
	</form>
	</div>
	</div>
	</div>
</div>
</div>

<script type="text/javascript">decorateTable('my-products-table');</script>
<script type="text/javascript">

<?php if($this->getRequest()->getActionName()=='index'){ ?>
	filterProducts(2);
<?php } ?>


jced('.product-list-checkstatus').change(function(){
	if(jced('.product-list-checkstatus option:selected').val()==1){
		jced('.product-list-status').show();
	}
	else{
		jced('.product-list-status').hide();
	}
		
});

function filterProducts(reset){
	var params ;
	if(reset==2)
    	reset=0;
	jced('#activity-loading').show();
	if(reset==1)
		params ='{reset_product_filter:1}';
	else
		params = jced("#product-list-form").serialize();
	new Ajax.Request("<?php 
							$urlParams['_nosid'] = true;
							if(Mage::app()->getStore()->isCurrentlySecure()){
    							$urlParams['_secure'] = true;
							}
    		echo  $this->getUrl('csmarketplace/vproducts/filter/store/'.$this->getRequest()->getParam('store',0),$urlParams) ?>", {
       method: 'Post',
       parameters:params,
       onComplete: function(transport) {
           jced('.vendor-dashboard').html(transport.responseText);
    	   jced('#activity-loading').hide();

       }
   });
}
  
	jced(document).ready(function(){
	  jced("#product-list-form").submit(function() {
				return false;
			});
	});   
   
   function setLocation(url){
	   jced('#activity-loading').show();
		new Ajax.Request(url, {
           method: 'Get',
           onComplete: function(transport) {
        	   jced('.vendor-dashboard').html(transport.responseText);
        	   jced('#activity-loading').hide();
           }
       });
   }
   
	jced('.pages a').click(function(e){	
		var url = jced(this).attr('href');
		if(url!="#"){
			jced('#activity-loading').show();
			e.preventDefault();
			new Ajax.Request(url, {
	           method: 'Get',
	           onComplete: function(transport) {
	               jced('.vendor-dashboard').html(transport.responseText);
	               jced('#activity-loading').hide();
	           }
	       });
		}
	});
 
</script>