<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php $helper=Mage::helper('csmarketplace');?>
<?php echo $this->getMessagesBlock()->getGroupedHtml()?>

<form name="form-validate"
	action="<?php //echo $this->getProductTypeUrl(); ?>"
	id="form-validate" method="post">
	<div class="row">
		<div class="col-md-12" style="margin-top:10px;">
			<div class="panel panel-default">
				<div class="panel-heading col-md-12" style="line-height:31px;font-size:17px;text-transform: uppercase;font-weight:bold;padding:4px 15px;">
				<?php echo $helper->__('Select')." ".$helper->__('Product Type') ?>
				</div>
				<?php 
					$types = Mage::getModel('csmarketplace/system_config_source_vproducts_type')->toOptionArray(false,true);
				?>
				<div class="panel-body">
					<div class="col-md-12">	
						<br/>
						<div class="form-group col-md-6">
							<label class="required"><em>*</em><?php echo $helper->__('Product Type') ?></label>:
							<div class="input-box">
								<select id="type" class="select validate-select form-control" name="type">
									<?php foreach($types as $type) { echo $type['label'];?>
										<?php if(!isset($type['value']) || !isset($type['label'])) continue; ?>
										<option value="<?php echo $type['value']; ?>"><?php echo $helper->__($type['label']); ?></option>
									<?php } ?>
								</select>
							</div>
						</div>	
						<div class="form-group col-md-12">	
							<script type="text/javascript">
							var url='<?php echo $this->getProductTypeUrl()?>';
							</script>
							<button class="btn btn-primary" onclick="if(dataForm.validator.validate()){setLocation('<?php echo $this->getProductTypeUrl()?>?type='+document.getElementById('type').value); return false;}" class="button" title="Continue" type="submit" id="continue"
							style="float: none;">
									<span><span><?php echo $this->__('Continue') ?></span></span>
							</button>
						</div>
					</div>
					<div class="col-md-12">
						<p class="back-link col-md-6" style="display:inline;" >
							<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo;
							</small><?php echo $helper->__('Back') ?></a>
						</p>
						<p style="display:inline;" class="required col-md-6"><?php echo $helper->__('* Required Fields') ?></p>
						<div style="clear:both;"></div>		
					</div>
			</div>
		</div>
	</div>
	</div>
</form>
<script type="text/javascript">

	//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
    </script>
