<?php echo $this->helper('adminhtml/media_js')->includeScript('dull/noflashuploader.js') ?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('dull/uploader.js') ?>

<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
    <div class="buttons" style="position:relative;float:right;">
        <div id="uploadBlocks" style="float:left;margin-right: 0.5em;"></div>
        <?php echo $this->getUploadButtonHtml() ?>
    </div>
    <div class="clear"></div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
        <div id="{{id}}" class="file-row">
        <span class="file-info">{{name}}</span>
        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
                                                           
<?php echo $this->getJsObjectName() ?> = new NoFlashUploader('<?php echo $this->getHtmlId() ?>', <?php echo $this->getConfigJson() ?>);

//]]>
</script>