 <?php 
 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * that is bundled with this package in the file LICENSE_AFL.txt.
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    design
  * @package     base_default
  * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
 
  $collection = $this->getCollection();
  $messages=$this->getinboxcollection();
 
 ?>
 
 <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header content-header-wrap">
          <h3>
            Customer Vendor Conversation Area
          </h3>
       </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="left-sidebar-wrap">
              <div class="box-header with-border box-folder">
                  <h3 class="box-title">Folders</h3>
              </div>
              
              <div class="box box-solid">
                
                <div class="box-body no-padding">
                  <ul class="nav nav-pills nav-stacked">
                    <li>
                      <a href="<?php echo Mage::getUrl('csvendorchat/frontend/customercompose')?>" class="btn btn-primary btn-block margin-bottom compose-tab">Compose</a>
                    </li>
                    <li class="active"><a href="<?php echo Mage::getUrl('csvendorchat/frontend/inbox')?>"> Inbox <span class="label label-primary pull-right"><?php if(count($messages)>0){ echo count($messages);}?></span></a></li>
                    <li><a href="<?php echo Mage::getUrl('csvendorchat/frontend/sent')?>" class="sent-mail-tab"> Sent</a></li>
                   <!--  <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
                    <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-waring pull-right">65</span></a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li> -->
                  </ul>
                </div><!-- /.box-body -->
              </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-inbox">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Inbox</h3>
                  <?php echo $this->getPagerHtml(); ?>
                  <div class="clear"></div>
                 <!--  <div class="box-tools pull-right">
                    <div class="has-feedback">
                      <input type="text" class="form-control input-sm" placeholder="Search Mail"/>
                      <span class="glyphicon glyphicon-search form-control-feedback"></span>
                    </div> -->
                  </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <div class="mailbox-controls">
                    <!-- Check all button -->
                   <!--  <div class="btn-group">
                      <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
                    </div> --><!-- /.btn-group -->
                   <!--  <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button> -->
                  <!--   <div class="pull-right">
                      1-50/200
                      <div class="btn-group">
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
                      </div> --><!-- /.btn-group -->
                    </div><!-- /.pull-right -->
                  </div>
                   <?php if(!$collection->count()): ?>
				  <p class="note-msg"><?php echo $this->__('There are no messages in your Inbox.') ?></p>
				   <?php else: ?>   
                  <div class="table-responsive mailbox-messages">
                    <table class="table table-hover table-striped">
                      <tbody>
                      <?php if($collection->getSize()): ?>
                      <?php foreach($collection as $msg=>$value):?>
                      
                        <tr>
                          <td class="mailbox-check><input class="chat_id" type="checkbox" value="<?php echo $value['chat_id']?>"/></td>
<!--                           <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
 -->                      <td class="mailbox-name"><a href="<?php echo Mage::getBaseUrl()?>csvendorchat/frontend/read?id=<?php echo $value['chat_id']?>"><?php echo $value['sender_email']?></a></td>
                          <td class="mailbox-subject"><b><?php echo $value['subject']?></b><?php echo substr($value['message'],0,16);?>...</td>
                          <td class="mailbox-attachment"></td>
                          <td class="mailbox-date"><?php echo $value['time']?></td>
                        </tr>
                       <?php
                        endforeach;?>
                        <?php endif;?>
                      </tbody>
                    </table><!-- /.table -->
                  </div><!-- /.mail-box-messages -->
                   <?php endif;?>
                </div><!-- /.box-body -->
                <div class="clear"></div>
                <div class="box-footer no-padding">
                  <div class="mailbox-controls">
                    <!-- Check all button -->
                   <!--  <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button> -->                    
               <!--      <div class="btn-group">
                      <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
                    </div> --><!-- /.btn-group -->
                 <!--    <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button> -->
                   <!--  <div class="pull-right">
                      1-50/200
                      <div class="btn-group">
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
                      </div> --><!-- /.btn-group -->
                    </div><!-- /.pull-right -->
                  </div>
                </div>
              </div><!-- /. box -->
           



    <!-- Page Script -->

