<?php $chat_id=$this->getRequest()->getParam('id');
      $chat=Mage::getModel('csvendorchat/chat')->load($chat_id);
      $originalDate =$chat->getTime();
      $newDate = date("d-F-Y H:m:s", strtotime($originalDate));
      $messages=$this->getinboxcollection()
      
      ?>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header content-header-wrap">
          <h3>
            Read Mail
          </h3>
  
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="left-sidebar-wrap">
              <div class="box-header with-border box-folder">
                  <h3 class="box-title">Folders</h3>
                </div>
              
              <div class="box box-solid">
                
                <div class="box-body no-padding">
                  <ul class="nav nav-pills nav-stacked">
                    <li>
                      <a href="<?php echo Mage::getUrl('csvendorchat/frontend/customercompose')?>" class="btn btn-primary btn-block margin-bottom">Compose</a>
                    </li>
                    <li><a href="<?php echo Mage::getUrl('csvendorchat/frontend/inbox')?>"><i class="fa fa-inbox"></i> Inbox <span class="label label-primary pull-right"><?php if(count($messages)>0){ echo count($messages);}?></span></a></li>
                    <li><a href="<?php echo Mage::getUrl('csvendorchat/frontend/sent')?>"><i class="fa fa-envelope-o"></i> Sent</a></li>
                  <!--   <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
                    <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-waring pull-right">65</span></a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li> -->
                  </ul>
                </div><!-- /.box-body -->
              </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-read">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Read Mail</h3>
                  <div class="pull-right">
                   <!--  <button class="btn btn-default"><i class="fa fa-reply"></i> Reply</button>
                    <button class="btn btn-default"><i class="fa fa-share"></i> Forward</button> -->
                    <!--<INPUT Type="button" VALUE="Back" class="back-btn btn btn-box-tool" >-->
                      <a href="" onClick="history.go(-1);return true;"><small><<</small>Back</a>
                  </div>
                  <div class="clear"></div>
                 <!-- <div class="box-tools pull-right">
                  <INPUT Type="button" VALUE="Back" class="btn btn-box-tool" onClick="history.go(-1);return true;">
                    <a href="" class="btn btn-box-tool" data-toggle="tooltip" title="Previous"><i class="fa fa-chevron-left"></i></a>
 --><!--                     <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Next"><i class="fa fa-chevron-right"></i></a>
                  </div>-->
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <div class="mailbox-read-info">
                    <h3><?php echo $chat->getSubject(); ?></h3>
                    <h5>From: <?php echo $chat->getSenderEmail(); ?> <span class="mailbox-read-time pull-right"><?php echo $newDate; ?></span></h5>
                  </div><!-- /.mailbox-read-info -->
             <!-- /.mailbox-controls -->
                  <div class="mailbox-read-message">
                  <?php echo $chat->getMessage()?>
                  </div><!-- /.mailbox-read-message -->
                </div><!-- /.box-body -->
              <!-- /.box-footer -->
                <div class="box-footer">
                  
                
                </div><!-- /.box-footer -->
              </div><!-- /. box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

