 <?php 
 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * that is bundled with this package in the file LICENSE_AFL.txt.
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    design
  * @package     base_default
  * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
 
 $collection = $this->getCollection();
 $messages=$this->getinboxcollection();

 ?>
 
 <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header content-header-wrap ">
          <h3>
             Customer Vendor Conversation Area
          </h3>
       </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="left-sidebar-wrap">
              <div class="box-header with-border box-folder">
                  <h3 class="box-title">Folders</h3>
                </div>
              
              <div class="box box-solid">
                
                <div class="box-body no-padding">
                  <ul class="nav nav-pills nav-stacked">
                    <li>
                      <a href="<?php echo Mage::getUrl('csvendorchat/frontend/customercompose')?>" class="btn btn-primary btn-block margin-bottom compose-tab">Compose</a>
                    </li>
                    <li><a href="<?php echo Mage::getUrl('csvendorchat/frontend/inbox')?>">Inbox <span class="label label-primary pull-right"><?php if(count($messages)>0){ echo count($messages);}?></span></a></li>
                    <li class="active"><a href="<?php echo Mage::getUrl('csvendorchat/frontend/sent')?>" class="sent-mail-tab">Sent</a></li>
                 
                  </ul>
                </div><!-- /.box-body -->
              </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-send">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Sent Box</h3>
                  <?php echo $this->getPagerHtml(); ?>
                  <div class="clear"></div>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <?php if(!$collection->count()): ?>
				  <p class="note-msg"><?php echo $this->__('There are no messages in your Inbox.') ?></p>
				   <?php else: ?>  
                   
                  <div class="table-responsive mailbox-messages">
                    <table class="table table-hover table-striped">
                      <tbody>
                        <?php if($collection->getSize()): ?>
                      <?php foreach($collection as $msg=>$value):?>
                        <tr>
                          <td class="mailbox-check"><input type="checkbox" value="<?php echo $value['chat_id']?>"/></td>
<!--                           <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
 -->                          <td class="mailbox-name"><a href="<?php echo Mage::getBaseUrl()?>csvendorchat/frontend/read?id=<?php echo $value['chat_id']?>"><?php echo $value['receiver_name']?></a></td>
                          <td class="mailbox-subject"><b><?php echo $value['subject']?></b><?php echo substr($value['message'],0,16);?>...</td>
                          <td class="mailbox-attachment"></td>
                          <td class="mailbox-date"><?php echo $value['time']?></td>
                        </tr>
                       <?php endforeach?>
                       <?php endif;?>
                      </tbody>
                    </table><!-- /.table -->
                  </div><!-- /.mail-box-messages -->
                  <?php endif;?>
                </div><!-- /.box-body -->
                <div class="box-footer no-padding">
                 
                </div>
              </div><!-- /. box -->
            </div><!-- /.col -->
            <div class="clear"></div>
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

