<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
 
?>
<?php
$helper = Mage::helper ( 'csmarketplace' );
$_product=Mage::registry('current_product');?>
<li class="wide">
							<label><?php echo $helper->__('Product Images') ?>:</label>
							<div class="input-box" >
								<div class="image_set">
							<?php 
							$productGalleryImages=array();
							$productGalleryImages =$_product->getMediaGalleryImages();
							$productImage = $_product->getImage();
							 if($_product->getId()) {  ?>
								<?php $i=0;
								  foreach($productGalleryImages as $_image) {
								  $check=($productImage==$_image->getFile())?"checked='checked'":'';
								  $i++; 
								  ?>
								  <div class="setimage">
								 <a def="<?php echo $_image->getFile(); ?>" onclick="imagePreview('<?php echo $_image->getFile(); ?>'); return false;" href="<?=$this->helper('catalog/image')->init($_product, 'image',$_image->getFile())->resize(600, 600);?>">
									  <img style="float:left" id="<?php echo $_image->getFile(); ?>" pid="<?php echo $_product->getId(); ?>" src="<?=$this->helper('catalog/image')->init($_product, 'thumbnail',$_image->getFile())->resize(600, 600); ?>" width="50" height="50" alt="<?=$this->htmlEscape($_image->getLabel());?>" title="<?=$this->htmlEscape($_image->getLabel()); ?>" >
									  </a>
									  <input  style="float:left;margin: 18px 0 11px 11px"  onClick="defaultSavedValue(this)" type="radio" name="defaultimage" <?php echo  $check ?>  class='defaultimage' value='<?php if($check!=='')echo $productImage; ?>'>
									  <span style="float:left;margin: 13px 11px 11px 0" class='defaultimageset'><?php echo $helper->__("Default Image"); ?></span>
									  <a style="float:left;margin:13px 11px 11px 0" href="javascript:;" onclick="removeSavedImage(this,'<?php echo $_image->getFile();?>','<?php echo $_product->getId()?>')"><?php echo $helper->__('Remove') ?></a>
								  </div>
								  <div style="clear:both"></div>
							   <?php  } 
							   } ?>
							    <input type="file" name="images[0]" class="dumimg imagevalidate" accept="image/*" size="33" />
								<input type="radio" value='' class='defaultimage' onClick='defaultvalue(this)' name="defaultimage"><span class='defaultimageset'><?php echo $helper->__("Default Image"); ?></span>
							</div>
								<div id="moreimages"></div>
								<a href="#" onClick="showMoreImages(); return false;"><?php echo $helper->__('Add')." ".$helper->__('More') ?></a>
								
							</div>
							
			</li>
<script type="text/javascript">
function showMoreImages(){
	var newdiv = document.createElement('div');
	newdiv.setAttribute("id","childDiv"+i);
	newdiv.innerHTML = "<input type='file' name='images["+i+"]' accept='image/\*' class='imagevalidate'/><input type='radio'  onClick='defaultvalue(this)'  value=''  class='defaultimage' name='defaultimage'><span class='defaultimageset'>Default image</span>&nbsp;&nbsp;<a href=\"javascript:;\" onclick=\"removeImageRow('childDiv"+i+"')\"><?php echo $helper->__('Remove') ?></a>";
	var ni = document.getElementById('moreimages');
	ni.appendChild(newdiv);
	i++;
}
function removeImageRow(divNum){
	var d = document.getElementById('moreimages');
	var olddiv = document.getElementById(divNum);
	d.removeChild(olddiv);
	i--;
}
function defaultvalue(object){
	var imgname = jced(object).prev('input').attr('name');
	jced('.defaultimage').each(function(){
		jced(this).val(null);
	});
	jced(object).val(imgname);
}

function defaultSavedValue(object){
	var imgname = jced(object).prev('a').attr('def');
	jced('.defaultimage').each(function(){
		jced(this).val(null);
	});
	jced(object).val(imgname);
}

function removeSavedImage(object,imagename,productid){
	var dicisionapp=confirm("<?php echo $helper->__('Are you sure?') ?>");
	if(dicisionapp==true){
 	   jced('#activity-loading').show();
		jced.ajax({
			url: "<?php echo $this->getUrl('csmarketplace/vproducts/deleteImage',array('_nosid'=>true));?>",
			type: "POST",
			data: {imagename:imagename,productid:productid,storeid:'<?php echo $_product->getStoreId()?>'},
			dataType: 'html',
			success:function(content){
				if(content==1){
					jced(object).parent('div').remove();
					alert("<?php echo $helper->__('Image Successfully Deleted') ?>");
				}
				else
					alert("<?php echo $helper->__('Error processing the request please Try Again') ?>");
				jced('#activity-loading').hide();
			}
		});
	}		
}

jced("body").delegate('.imagevalidate',"change",function(){
	var ext = jced(this).val().split('.').pop().toLowerCase();
	if(jced.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {
		jced(this).val('');
	    alert("<?php echo $helper->__('Invalid extension! Please Upload an image') ?>");
	}
});
</script>