<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<li class="wide"><label><?php echo $this->__('Websites') ?>:</label>
	<div class="input-box category">
            <?php foreach ($this->getWebsiteCollection() as $_website): ?>
            <div class="website-name">
                <input name="product[website_ids][]" value="<?php echo $_website->getId() ?>" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif;?> class="checkbox website-checkbox" id="product_website_<?php echo $_website->getId() ?>" type="checkbox"<?php if($this->hasWebsite($_website->getId())): ?> checked="checked"<?php endif; ?> />
                <big><strong><label  style="float:none;font-weight:bold;font-size: 14px;" for="product_website_<?php echo $_website->getId() ?>"><?php echo $this->escapeHtml($_website->getName()) ?></label></strong></big>
            </div>
            <div style="padding-left:25px" class="webiste-groups" id="product_website_<?php echo $_website->getId() ?>_data">
            <?php foreach ($this->getGroupCollection($_website) as $_group): ?>
                <label><?php echo $this->escapeHtml($_group->getName()) ?></label>
                <div style="clear:both"></div>
                <div style="padding-left:15px" class="group-stores">
                <table>
                <?php foreach ($this->getStoreCollection($_group) as $_store): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($_store->getName()) ?></td>
                    </tr>
                <?php endforeach; ?>
                </table>
                </div>
            <?php endforeach; ?>
            </div>
            <?php endforeach; ?>
        </div>
</li>
