<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php 
$helper = Mage::helper ( 'csmarketplace' );
$params = Mage::getSingleton('core/session')->getData('vorders_reports_filter');
?>
 <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form
	action=""
	method="post"
	id="report-form-validate">
	
	<div class="col-md-12">
		<h4 class="legend" ><?php echo $helper->__('Filter Report') ?>
		</h4>		
		<div style="clear:both"></div>
			<div class="form-group col-md-3">
				<label><?php echo $helper->__('Period') ?>:</label>
				<div class="input-box">
					<select id="period" class="select form-control"
						name="period">
						<option <?php echo isset($params['period']) && $params['period']=='day'?"selected":"";?> value="day"><?php echo $helper->__('Day'); ?></option>
						<option <?php echo isset($params['period']) && $params['period']=='month'?"selected":"";?> value="month"><?php echo $helper->__('Month'); ?></option>
						<option <?php echo isset($params['period']) && $params['period']=='year'?"selected":"";?> value="year"><?php echo $helper->__('Year'); ?></option>
					</select>
				</div>
			</div>
			
			<div class="form-group col-md-3">
				<label ><?php echo $helper->__('Vendor Payment Status') ?>:</label>
				<div class="input-box">
					<select id="payment_state" name="payment_state" class="select form-control"
						>
						<option  <?php echo isset($params['payment_state']) && $params['payment_state']=="*"?> value="*"><?php echo $helper->__('All'); ?></option>
						<option  <?php echo isset($params['payment_state']) && $params['payment_state']==Ced_CsMarketplace_Model_Vorders::STATE_OPEN?"selected":"";?> value="<?php echo Ced_CsMarketplace_Model_Vorders::STATE_OPEN ?>"><?php echo $helper->__('Pending'); ?></option>
						<option  <?php echo isset($params['payment_state']) && $params['payment_state']==Ced_CsMarketplace_Model_Vorders::STATE_PAID?"selected":"";?>  value="<?php echo Ced_CsMarketplace_Model_Vorders::STATE_PAID ?>""><?php echo $helper->__('Paid'); ?></option>
						<option  <?php echo isset($params['payment_state']) && $params['payment_state']==Ced_CsMarketplace_Model_Vorders::STATE_CANCELED?"selected":"";?> value="<?php echo Ced_CsMarketplace_Model_Vorders::STATE_CANCELED ?>""><?php echo $helper->__('Cancelled'); ?></option>
					</select>
				</div>
			</div>
			
			<div class="form-group col-md-3">
				<label class="required"><em>*</em><?php echo $helper->__('Start date') ?>:</label>
				<div class="input-box">
					<img style="padding:7px;float:left" src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle" id="from_date_cal" />
					<input type="text" class="required-entry input-text validate-date form-control" style="width:110px" name="from"
						id="from" value="<?php echo isset($params['from']) && ($params['from']!="")?$params['from']:""; ?>"/>
				</div>
			</div>
			
			<div class="form-group col-md-3">
				<label class="required"><em>*</em><?php echo $helper->__('End date') ?>:</label>
				<div class="input-box">
					<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" style="padding:7px;float:left" class="v-middle" id="to_date_cal" />
					<input type="text" class="required-entry input-text validate-date form-control" style="width:110px;" name="to"
						id="to" value="<?php echo isset($params['to']) && ($params['to']!="")?$params['to']:""; ?>"/>
				</div>
			</div>
	</div>
	<div class="col-md-12" style="margin-bottom:5px;">
		<div class="col-md-6" style="padding-left:0;margin-bottom:5px;padding-right:0;">
			<button class="button btn btn-warning uptransform" title="<?php echo $helper->__('Export') ?>" onClick="window.location='<?php echo $this->getUrl('*/*/exportVordersCsv',array('_secure'=>true,'_nosid'=>true))?>'" id="export_btn"
				style="float: none;display:none">
				<span><span><?php echo $helper->__('Export') ?></span></span>
			</button>
		</div>
		<div class="col-md-6"  id="filter_butn6" style="margin-left:0;margin-bottom:5px;padding-right:0;text-align:right;display:none;">
			<button class="button btn btn-info uptransform" title="<?php echo $helper->__('Show Report') ?>" onClick="filterVordersReports(0);" id="filter_butn"
				style="float: none;">
				<span><span><?php echo $helper->__('Show Report') ?></span></span>
			</button>
		</div>
		<div class="col-md-12" id="filter_butn12" style="margin-left:0;margin-bottom:5px;padding-right:0;text-align:right;">
			<button class="button btn btn-info uptransform" title="<?php echo $helper->__('Show Report') ?>" onClick="filterVordersReports(0);" id="filter_butn"
				style="float: none;">
				<span><span><?php echo $helper->__('Show Report') ?></span></span>
			</button>
		</div>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('report-form-validate', true);
    setTimeout(function(){
    	Calendar.setup({
    	    inputField : 'from',
    	    ifFormat : '%m/%e/%y',
    	    button : 'from_date_cal',
    	    align : 'Bl',
    	    singleClick : true
    	});

    	Calendar.setup({
    	    inputField : 'to',
    	    ifFormat : '%m/%e/%y',
    	    button : 'to_date_cal',
    	    align : 'Bl',
    	    singleClick : true
    	});
    	}, 500);
//]]>
    function filterVordersReports(reset){
    	if(reset==2){
        	reset=0;
        	jced('#activity-loading').show();
    	}
    	else{
    		if(!dataForm.validator.validate())
           	 	return;
    	 	jced('#activity-loading').show();
    	}
    	var params ;
    	
    	params = jced("#report-form-validate").serialize();
    	new Ajax.Request("<?php 
    	$urlParams['_nosid'] = true;
    	if(Mage::app()->getStore()->isCurrentlySecure()){
    		$urlParams['_secure'] = true;
    	}
    	echo   $this->getUrl('csmarketplace/vreports/filtervorders',$urlParams) ?>", {
           method: 'Post',
           parameters:params,
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
        	   jced('#activity-loading').hide();

           }
       });
    }
    jced(document).ready(function(){
    	  jced("#report-form-validate").submit(function() {
    				return false;
    			});
    	});   
</script>
<style>
   label.required em, span.required em {
    display: none;
}
label.required::after, span.required::after {
    color: red;
    content: " *";
    font-family: "Helvetica Neue",Verdana,Arial,sans-serif;
    font-size: 12px;
    font-weight: normal;
}
</style>