<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php $helper = Mage::helper ( 'csmarketplace' );?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getVordersReports(); 
?>

<div style="clear:both"></div>
<form id="payment_form"
	action=""
	enctype="multipart/form-data" method="post">
<?php if(count($collection)>0){?>
<script type="text/javascript">
jced('#export_btn').show();
jced('#filter_butn6').show();
jced('#filter_butn12').hide();
</script>
<?php }?>
<div class="order-items order-details table-responsive">
		<table id="my-products-table" class="table table-bordered table-hover table-striped">
	    <col width="2"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
		<thead>	
			<tr>
				<th class="head"><?php echo $this->__('Period') ?></th>
		        <th class="head"><?php echo $this->__('Orders') ?></th> 
		        <th class="head"><?php echo $this->__('Sales Items') ?></th>
				<th class="head"><?php echo $this->__('Total Sales') ?></th>
				<th class="head"><?php echo $this->__('Total Commission') ?></th>
				<th class="head"><?php echo $this->__('Net Sales') ?></th>
			</tr>		
	    </thead>
	    <tbody>
		<?php if(count($collection)>0): ?>
	    <?php $_odd = ''; ?>
	    <?php foreach ($collection as $_report): ?>
	        <tr>
	            <td class="number"><?php echo $_report->getPeriod();	 ?></td>
	            <td class="date"><?php echo $_report->getOrderCount() ?></td>
				<td class="number"><?php echo $_report->getProductQty() ?></td>     
	            <td class="status"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getBaseCurrencyCode())->toCurrency($_report->getOrderTotal());  ?></td>
	            <td class="status"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getBaseCurrencyCode())->toCurrency($_report->getCommissionFee());  ?></td>
				<td class="number"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getBaseCurrencyCode())->toCurrency($_report->getNetEarned());  ?></td>
	        </tr>
	        <?php endforeach; ?>
			<?php else: ?>
			<tr>
				<td colspan="6">
					<div>
					<p class="not_avail"><?php echo $this->__('No Report Available'); ?></p>
					</div>
				</td>
			</tr>		
			<?php endif ?>
		</tbody>
	</table>
</div>
</form>
<p class="required"><?php echo $helper->__('* Required Fields') ?></p>
<script type="text/javascript">decorateTable('my-orders-table');</script>

<script type="text/javascript">
<?php if($this->getRequest()->getActionName()=='vorders'){ ?>
	filterVordersReports(2);
<?php } ?>
  
	jced(document).ready(function(){
	  jced("#payment_form").submit(function() {
				return false;
			});
	});

	 function setLocation(url){
		  jced('#activity-loading').show();
			new Ajax.Request(url, {
	           method: 'Get',
	           onComplete: function(transport) {
	               jced('.vendor-dashboard').html(transport.responseText);
	        	   jced('#activity-loading').hide();
	           }
	       });
	   }
	   
	 jced('.pages a').click(function(e){	
			var url = jced(this).attr('href');
			if(url!="#"){
				jced('#activity-loading').show();
				e.preventDefault();
				new Ajax.Request(url, {
		           method: 'Get',
		           onComplete: function(transport) {
		               jced('.vendor-dashboard').html(transport.responseText);
		               jced('#activity-loading').hide();
		           }
		       });
			}
		});
</script>


