<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
$vendor_id=Mage::getSingleton('customer/session')->getVendorId();
$vendor=Mage::getModel('csvendorvacation/vacation')->getCollection()->addFieldToFilter('vendor_id',$vendor_id)->getData();
$vendordata=$vendor[0];
$vendor_csmarketplace = Mage::getModel('csmarketplace/vendor')->load($vendor_id);
$vendor_url =$vendor_csmarketplace->getShopUrl();
$vendor_name = $vendor_csmarketplace->getName();


var_dump($vendor_public_name);
if(Mage::getSingleton('customer/session')->isLoggedIn()){

if($vendordata['status']=='0'){

      if($vendordata['show_hide']=='3'){      ?>
	<div class="admin_vacational_msg">
	<span>Vendor <?php echo $vendor_name;?> is On Vacation. You can buy their Products from their Shop "<?php echo $vendor_url;?>". But The Products Will Be Delivered</span>
	<span>When he Returns From the Vacation</span>
	</div>
	<div class="vendor-msg">
	<?php echo $vendordata['vendormsg']?>
	</div>
<?php 
   }
  }
}

?>