<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php $collection = $this->getVorders(); 
$statusArray=Mage::getModel('sales/order_invoice')->getStates();
$params = Mage::getSingleton('core/session')->getData('order_filter');
$paymentarray=Mage::getModel('csmarketplace/vorders')->getStates();
?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
			<div  style="line-height:31px;font-size:17px;display:inline;text-transform: uppercase;">
			<?php echo $this->__('Orders List') ?>
			</div>
         </div>
 	<div class="panel-body">
 	<div class="col-md-12" style="margin-top:10px;">
<form
	action=""
	enctype="multipart/form-data" id="payment_form" method="post"
	>
	<div class="vendor-button-set buttons-set filter_button">
	<?php if(count($collection)>0){ ?>
		<div class="col-md-4 export-button" style="padding-left:0;">
			<button onClick="window.location='<?php echo $this->getUrl('*/*/exportCsv',array('_secure'=>true, '_nosid'=>true)); ?>'" class="uptransform btn btn-warning button" title="Export Orders" style="margin:2px; float:left;">
						<span><span><?php echo $this->__('Export') ?></span></span>
			</button>
		</div>
	<div class="col-md-8 filter-buttons" style="margin-left:0;padding-right:0;text-align:right;">
	<?php }
	else{ 
		 ?>
		<div class="col-md-12" style="margin-left:0;margin-bottom:5px;padding-right:0;text-align:right;">
	<?php }?>
		<button  style="margin:2px" onClick="filterPayment(0);" class="button btn btn-info uptransform " title="<?php echo $this->__('Filter') ?>" type="submit" id="Filter"	>
			<span><span><?php echo $this->__('Filter') ?></span></span>
		</button> 
		<button  style="margin:2px" onClick="filterPayment(1);" class="button btn btn-info uptransform" title="<?php echo $this->__('Reset Filter') ?>" type="button" id="Filter"	>
			<span><span><?php echo $this->__('Reset Filter') ?></span></span>
		</button>
		</div>
		<div style="clear:both"></div>
	</div>	
	
<br/>
<?php echo $this->getPagerHtml(); ?>
<div style="clear:both"></div>
<div class="order-items order-details table-responsive">
		<table id="my-products-table" class="table table-bordered table-hover table-striped">
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <thead>
	    	<tr style="background-color: #f5f5f5;">
				<th class="head"><?php echo $this->__('Order Id #') ?></th>
				<th class="head"><?php echo $this->__('Purchased On') ?></th>
				<th class="head"><?php echo $this->__('Bill To Name') ?></th>
				<th class="head"><?php echo $this->__('G.T.') ?></th>
				<th class="head"><?php echo $this->__('Commission')." " ?><?php echo $this->__('Fee') ?></th>
				<th class="head"><?php echo $this->__('Net Earned') ?></th>
				<th class="head"><?php echo $this->__('Order')." " ?><?php echo $this->__('Payment')." " ?><?php echo $this->__('Status') ?></th>
	            <th class="head"><?php echo $this->__('Vendor')." " ?><?php echo $this->__('Payment')." " ?><?php echo $this->__('Status') ?>
			</tr>
         	<tr class="filter">
              	<th class="filter">
		        	<div class="list_filter"><input type="text" class="form-control filter" name="increment_id"   value="<?php echo (isset($params['increment_id']) && urldecode($params['increment_id'])!="")?urldecode($params['increment_id']):""; ?>" /></div>
		        </th>
		        
		        <th class="filter">
		        	<div class="list_filter">
	        		<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle " id="date_from_trig" />
					<input type="text" id="created_at_from" name="created_at[from]" class="form-control" value="<?php echo (isset($params['created_at']['from']) && urldecode($params['created_at']['from'])!="")?urldecode($params['created_at']['from']):""; ?>" /></div>
					<div class="list_filter">
					<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle" id="date_to_trig" />
					<input type="text"  id="created_at_to" name="created_at[to]" class="form-control" value="<?php echo (isset($params['created_at']['to']) && urldecode($params['created_at']['to'])!="")?urldecode($params['created_at']['to']):""; ?>"  /></div>
		        </th>
		        
		        <th class="filter">
		        	<div class="list_filter"><input type="text" name="billing_name"  class="filter form-control" value="<?php echo (isset($params['billing_name']) && urldecode($params['billing_name'])!="")?urldecode($params['billing_name']):""; ?>" /></div>
				</th> 
				
		        <th class="filter">
		           <div class="list_filter"><input type="text" name="order_total[from]" class="filter form-control"  value="<?php echo (isset($params['order_total']['from']) && urldecode($params['order_total']['from'])!="")?urldecode($params['order_total']['from']):""; ?>" /></div>
				<div class="list_filter"><input type="text" name="order_total[to]" class="filter form-control" value="<?php echo (isset($params['order_total']['to']) && urldecode($params['order_total']['to'])!="")?urldecode($params['order_total']['to']):""; ?>"  /></div>
				</th>
				
		  		<th class="filter">
		            <div class="list_filter"><input type="text" name="shop_commission_fee[from]" class="filter form-control"  value="<?php echo (isset($params['shop_commission_fee']['from']) && urldecode($params['shop_commission_fee']['from'])!="")?urldecode($params['shop_commission_fee']['from']):""; ?>" /></div>
				<div class="list_filter"><input type="text" name="shop_commission_fee[to]" class="filter form-control" value="<?php echo (isset($params['shop_commission_fee']['to']) && urldecode($params['shop_commission_fee']['to'])!="")?urldecode($params['shop_commission_fee']['to']):""; ?>"  /></div>
		       	</th>
		       	
		      	<th class="filter">
		            <div class="list_filter"><input type="text" name="net_vendor_earn[from]" class="filter form-control"  value="<?php echo (isset($params['net_vendor_earn']['from']) && urldecode($params['net_vendor_earn']['from'])!="")?urldecode($params['net_vendor_earn']['from']):""; ?>" /></div>
				<div class="list_filter"><input type="text" name="net_vendor_earn[to]" class="filter form-control" value="<?php echo (isset($params['net_vendor_earn']['from']) && urldecode($params['net_vendor_earn']['to'])!="")?urldecode($params['net_vendor_earn']['to']):""; ?>"  /></div>
		        </th>
		        
		       	<th class="filter">
		      		 <div class="product-list-filter">
					<select style="width:56px" type="text" name="order_payment_state" class="filter input-select-small product-list-checkstatus form-control" value="">
	            	<option value=""></option>
	           		<?php foreach($statusArray as $val=>$label) { ?>
								<option <?php echo (isset($params['order_payment_state']) && urldecode($params['order_payment_state'])==$val)?"selected":"";?> value="<?php echo $val; ?>"><?php echo $this->__($label); ?></option>
							<?php } ?>
	            	</select></div>
		  		</th>
		            
              	<th class="filter">
              		<div class="product-list-filter">
					<select style="width:56px" type="text" name="payment_state" class="form-control filter input-select-small product-list-checkstatus" value="">
	            	<option value=""></option>
	           		<?php foreach($paymentarray as $val=>$label) { ?>
								<option <?php echo (isset($params['payment_state']) && urldecode($params['payment_state'])==$val)?"selected":"";?> value="<?php echo $val; ?>"><?php echo $this->__($label); ?></option>
							<?php } ?>
	            	</select></div>
              	</th>
           	</tr>
	    </thead>
	    <?php if(count($collection)>0): ?>
	    <tbody>
	        <?php $_odd = ''; ?>
	        <?php foreach ($collection as $_order):
			?>
	        <tr>
	            <td class="number"><a  title="Click to view Order Details" href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getIncrementId() ?></a></td>
	            <td class="status"><?php echo  Mage::helper('core')->formatDate( $_order->getCreatedAt() , 'medium', true);	 ?></td>
				<td class="status"><?php echo $_order->getBillingName() ?></td>   
				<td class="date">
					<?php 
					echo Mage::app()->getLocale()->currency($_order->getCurrency())->toCurrency($_order->getOrderTotal()) ?>
				</td>
				<td class="date">
					<?php 
					echo Mage::app()->getLocale()->currency($_order->getCurrency())->toCurrency($_order->getShopCommissionFee()) ?>
				</td>
				<td class="date">
					<?php 
					echo Mage::app()->getLocale()->currency($_order->getCurrency())->toCurrency($_order->getNetVendorEarn()) ?>
				</td>
				<td class="number"><?php echo $this->__($statusArray[$_order->getOrderPaymentState()]) ?></td>
				<td class="number"><?php echo $this->__($paymentarray[$_order->getPaymentState()]) ?></td>
	     		
	        </tr>
	        <?php endforeach; ?>
	        <?php else: ?>
			<tr>
				<td colspan="8">
				<div>
				<p><?php echo $this->__('No Orders Available'); ?></p>
				</div>
				</td>
			</tr>		
			<?php endif ?>
	    </tbody>
	</table>
</div>
<?php echo $this->getPagerHtml(); ?>
</form>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">decorateTable('my-orders-table');</script>

<script type="text/javascript">// <![CDATA[
setTimeout(function(){
Calendar.setup({
    inputField : 'created_at_from',
    ifFormat : '%m/%e/%y',
    button : 'date_from_trig',
    align : 'Bl',
    singleClick : true
});

Calendar.setup({
    inputField : 'created_at_to',
    ifFormat : '%m/%e/%y',
    button : 'date_to_trig',
    align : 'Bl',
    singleClick : true
});
}, 500);
// ]]></script>
<style>
#date_from_trig, #date_to_trig{
float:left;
}					
</style>
<script type="text/javascript">
<?php if($this->getRequest()->getActionName()=='index'){ ?>
	filterPayment(2);
  <?php } ?>
  
	jced(document).ready(function(){
	  jced("#payment_form").submit(function() {
				return false;
			});
	});


function filterPayment(reset){
		var params ;
		if(reset==2)
        	reset=0;
    	jced('#activity-loading').show();
		if(reset==1)
			params ='{reset_order_filter:1}';
		else
			params = jced("#payment_form").serialize();

		new Ajax.Request("<?php 
		$urlParams['_nosid'] = true;
		if(Mage::app()->getStore()->isCurrentlySecure()){
			$urlParams['_secure'] = true;
		}
		echo   $this->getUrl('csmarketplace/vorders/filter',$urlParams) ?>", {
           method: 'Post',
           parameters:params,
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
               jced('#activity-loading').hide();

           }
       });
   }
   
   
  function setLocation(url){
	  jced('#activity-loading').show();
		new Ajax.Request(url, {
           method: 'Get',
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
               jced('#activity-loading').hide();
           }
       });
   }
   
  jced('.pages a').click(function(e){	
		var url = jced(this).attr('href');
		if(url!="#"){
			jced('#activity-loading').show();
			e.preventDefault();
			new Ajax.Request(url, {
	           method: 'Get',
	           onComplete: function(transport) {
	               jced('.vendor-dashboard').html(transport.responseText);
	               jced('#activity-loading').hide();
	           }
	       });
		}
	});
 
</script>