<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="col-md-8 col-md-offset-2">
    <div class="login-panel panel panel-default">
		<div class="panel-heading" style="text-align: center;font-weight:bold;">
			<h3 style="font-size:20px;" class="panel-title"><?php echo Mage::helper('customer')->__('You are now logged out') ?></h3>
		</div>
		<div class="panel-body">
			<?php echo Mage::helper('csmarketplace')->__('You have logged out and will be redirected to login page in 5 seconds.') ?>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    setTimeout(function(){ location.href = '<?php echo Mage::helper('csmarketplace')->getVendorUrl(); ?>'},5000);
//]]>
</script>
