<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="col-md-4 col-md-offset-4">
	<div class="forgot-panel panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?php echo $this->__('Forgot Your Password?') ?></h3>
		</div>
		<div class="panel-body">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
			<form action="<?php echo Mage::getUrl('csmarketplace/account/forgotpasswordpost', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));//$this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
				<fieldset>
					<h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
					<p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
					<div class="input-box">
						<input placeholder="<?php echo $this->__('Email Address') ?>" type="text" name="email" alt="email" id="email_address" class="form-control input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
					</div>
				</fieldset>
				<div class="buttons-set">
					<p class="back-link"><a href="<?php echo Mage::getUrl('csmarketplace/account/login', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));//$this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
					<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				</div>
			</form>
		</div>
	</div>
	<script type="text/javascript">
	//<![CDATA[
		var dataForm = new VarienForm('form-validate', true);
	//]]>
	</script>
</div>
