<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
		<div class="panel-heading" style="text-align: center;font-weight:bold;">
			<!--h3 style="font-size:20px;" class="panel-title"><?php //echo $this->__('Vendor Login') ?></h3-->
			<h3 style="font-size:20px;" class="panel-title">Iniciar sesión</h3>
		</div>
		<div class="panel-body">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
			<form action="<?php echo Mage::getUrl('csmarketplace/account/loginPost', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));//$this->getPostActionUrl() ?>" method="post" id="login-form" role="form">
				<?php echo $this->getBlockHtml('formkey'); ?>
				<fieldset>
					<div class="col2-set">
						<div class="col-2 registered-users">
							<div class="content">
								<!--p><?php echo $this->__('If you have a vendor account with us, please log in.') ?></p-->
								<p>Si ya tienes una cuenta de vendedor con nosotros por favor ingresa tus datos</p>
								
								<div class="form-group input-box">
									<!--<span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span> -->
									<input type="email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="form-control input-text required-entry validate-email" placeholder="<?php echo $this->__('Email Address') ?>" title="<?php echo $this->__('Email Address') ?>" autofocus/>
								</div>
							
								<div class="form-group input-box">
									<!-- <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span> -->
									<input type="password" name="login[password]" class="form-control input-text required-entry validate-password" placeholder="<?php echo $this->__('Password') ?>" id="pass" title="<?php echo $this->__('Password') ?>" />
								</div>
							
								<div class="checkbox">
									<label>
										<input name="remember" type="checkbox" value="<?php echo 'Recordarme'; //$this->__('Remember Me'); ?>"><?php echo 'Recordarme'; //$this->__('Remember Me'); ?>
									</label>
								</div> 
								<button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
							</div>
						</div>
					</div>
					<div class="col2-set">
						<div class="col-1 new-users">
							<div class="buttons-set">
								<a href="<?php echo Mage::getUrl('csmarketplace/account/forgotpassword', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));//$this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
							</div>
						</div>
						<div class="col-2 registered-users">
							<?php if(Mage::getStoreConfig('ced_csmarketplace/general/enable_registration')) { ?>
							<div class="buttons-set" style="float:left;">
								<a href='<?php echo Mage::getUrl('csmarketplace/account/create', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));//$this->getCreateAccountUrl() ?>'><?php echo $this->__('Create an Account') ?></a>
							</div>
							<?php } ?>
							<div class="buttons-set" style="float:right;">
					        <a href='<?php echo Mage::getBaseUrl();//$this->getCreateAccountUrl() ?>'><?php echo $this->__('Back') ?></a>
					       </div>
					       <div style="clear:both;"></div>
						</div>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>