<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Create account form template
 *
 * @see Mage_Customer_Block_Form_Register
 */
?>
<div class="col-md-8 col-md-offset-2">
	<div class="register-panel panel panel-default">
		<div class="panel-heading">
			<h1><?php echo $this->__('Create a Vendor Account') ?></h1>
		</div>
		<div class="panel-body">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
			<form action="<?php echo Mage::getUrl('csmarketplace/account/createPost', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));?>" method="post" id="form-validate" role="form">
				<fieldset>
					<div class="panel panel-default">
						<?php echo $this->getBlockHtml('formkey') ?>
						<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
						<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
						<div class="panel-heading"><?php echo $this->__('Personal Information') ?></div>
						<div class="panel-body">
							<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
						
								<div class="input-box email">
									<input placeholder="<?php echo $this->__('Email Address') ?>" type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="form-control input-text validate-email required-entry" />
								</div>
							
							<?php if ($this->isNewsletterEnabled()): ?>
							
								<div class="checkbox">
									<label>
										<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />  <?php echo $this->__('Sign Up for Newsletter') ?>
									</label>
								</div>
							<?php endif ?>
							<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
							<?php if ($_dob->isEnabled()): ?>
								<?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
							<?php endif ?>
							<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
							<?php if ($_taxvat->isEnabled()): ?>
								<?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
							<?php endif ?>
							<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
							<?php if ($_gender->isEnabled()): ?>
								<?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
							<?php endif ?>
						</div>
					</div>
				</fieldset>
				<?php 
				if(version_compare(Mage::getVersion(), '1.6', '>=') && Mage::helper('csmarketplace/acl')->isEnabled()) {
					echo $this->getChildHtml('vendorRegForm');
				}
				?>
			<?php if($this->getShowAddressFields()): ?>
				<fieldset>
					<div class="panel panel-default">
						<div class="panel-heading">
							<input type="hidden" name="create_address" value="1" />
							<?php echo $this->__('Address Information') ?>
						</div>
						<div class="panel-body">
							<ul class="form-list nav">
								<li class="fields">
									<div class="field">
										<div class="input-box">
											<input placeholder="<?php echo $this->__('Company') ?>" type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="form-control input-text" />
										</div>
									</div>
									<div class="field">
										<div class="input-box">
											<input placeholder="<?php echo $this->__('Telephone') ?>" type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="form-control input-text required-entry" />
										</div>
									</div>
								</li>
								<li class="wide">
									<div class="input-box">
										<input placeholder="<?php echo $this->__('Street Address') ?>" type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="form-control input-text required-entry" />
									</div>
								</li>
							<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
								<li class="wide">
									<div class="input-box">
										<input placeholder="<?php echo $this->__('Street Address') ?>" type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="form-control input-text" />
									</div>
								</li>
							<?php endfor ?>
								<li class="fields">
									<div class="field">
										<div class="input-box">
											<input placeholder="<?php echo $this->__('City') ?>" type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="form-control input-text required-entry" id="city" />
										</div>
									</div>
									<div class="field">
										<div class="input-box">
											<select placeholder="<?php echo $this->__('State/Province') ?>" id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
												<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
											</select>
											<script type="text/javascript">
											//<![CDATA[
												$('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
											//]]>
											</script>
											<input placeholder="<?php echo $this->__('State/Province') ?>" type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="form-control input-text" style="display:none;" />
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<div class="input-box">
											<input placeholder="<?php echo $this->__('Zip/Postal Code') ?>" type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="form-control input-text validate-zip-international required-entry" />
										</div>
									</div>
									<div class="field">
										<label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect() ?>
										</div>
									</div>
								</li>
							</ul>
							<input type="hidden" name="default_billing" value="1" />
							<input type="hidden" name="default_shipping" value="1" />
						 </div>
					 </div>
				</fieldset>
			<?php endif; ?>
				<fieldset>
					<div class="panel panel-default">
						<div class="panel-heading"><?php echo $this->__('Login Information') ?></div>
						<div class="panel-body">
							<div class="field">
								
								<div class="input-box">
									<input placeholder="<?php echo $this->__('Password') ?>" type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="form-control input-text required-entry validate-password" />
								</div>
							</div>
							<div class="field">
								
								<div class="input-box">
									<input placeholder="<?php echo $this->__('Confirm Password') ?>" type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="form-control input-text required-entry validate-cpassword" />
								</div>
							</div>
						</div>						
					</div>
				</fieldset>
				<div class="content">
					<div class="buttons-set">
						<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
						<p class="back-link"><a href="<?php echo Mage::getUrl('csmarketplace/account/login', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()));//$this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
					</div>
				</div>
			</form>
		</div>
	</div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
