<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php $helper=Mage::helper('csmarketplace');?>
<?php 
$types = Mage::getModel('csmarketplace/system_config_source_vproducts_type')->toOptionArray(false,true);
?>
<div class="page-title">
	<h1><i class="fa fa-plus-square fa-fw"></i> <?php echo $helper->__('Select')." ".$helper->__('Product Type') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
<form name="form-validate"
	action="<?php //echo $this->getProductTypeUrl(); ?>"
	id="form-validate" method="post">
	<div class="fieldset">
		<ul class="form-list" id="cs_bodymain">
			<!-- <li><label class="required"><em>*</em><?php //echo $helper->__('Attribute Set') ?>:</label>
				
				<div class="input-box">
					<select id="set" class="select validate-select" name="set">
						<?php //foreach ($sets as $set){ ?>
							<?php //if(!isset($set['value']) || !isset($set['label'])) continue; ?>
							<option value="<?php //echo $set['value'];?>"><?php //echo $helper->__($set['label']); ?></option>	
						<?php //} ?>
					</select>
				</div>
			</li> -->
			<li><label class="required"><em>*</em><?php echo $helper->__('Product Type') ?>:</label>
				<div class="input-box">
					<select id="type" class="select validate-select" name="type">
						<?php foreach($types as $type) { echo $type['label'];?>
							<?php if(!isset($type['value']) || !isset($type['label'])) continue; ?>
							<option value="<?php echo $type['value']; ?>"><?php echo $helper->__($type['label']); ?></option>
						<?php } ?>
					</select>
				</div>
			</li>
		</ul>
	</div>
	<div class="buttons-set">
		<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		<script type="text/javascript">
		var url='<?php echo $this->getProductTypeUrl()?>';
		</script>
		<button onclick="setLocation('<?php echo $this->getProductTypeUrl()?>type/'+document.getElementById('type').value); return false;" class="button" title="Continue" type="submit" id="continue"
			style="float: none;">
			<span><span><?php echo $this->__('Continue') ?></span></span>
		</button>
		<p class="back-link">
			<a
				href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo;
			</small><?php echo $helper->__('Back') ?></a>
		</p>
	</div>
</form>
<script type="text/javascript">

	//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
    </script>