<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php if ($websites = $this->getWebsites()): ?>
<p class="switcher"><label for="store_switcher"><?php echo $this->__('Choose Store View') ?>:</label>
<br/>
<ul style="list-style:none;">
<li class="wide">
<select name="store_switcher" id="store_switcher" onchange="return switchStore(this);">
<?php if ($this->hasDefaultOption()): ?>
    <option value=""><?php echo $this->getDefaultStoreName() ?></option>
<?php endif; ?>
    <?php foreach ($websites as $website): ?>
        <?php $showWebsite=false; ?>
        <?php foreach ($website->getGroups() as $group): ?>
            <?php $showGroup=false; ?>
            <?php foreach ($this->getStores($group) as $store): ?>
                <?php if ($showWebsite == false): ?>
                    <?php $showWebsite = true; ?>
                    <optgroup label="<?php echo $website->getName() ?>"></optgroup>
                <?php endif; ?>
                <?php if ($showGroup == false): ?>
                    <?php $showGroup = true; ?>
                    <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $group->getName() ?>">
                <?php endif; ?>
                <option value="<?php echo $store->getId() ?>"<?php if($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $store->getName() ?></option>
            <?php endforeach; ?>
            <?php if ($showGroup): ?>
                </optgroup>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
</select>
</li>
</ul>
</p>
<script type="text/javascript">
    function switchStore(obj){
        var storeParam = obj.value ? 'store/'+obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
    <?php if($this->getUseConfirm() && $this->getRequest()->getActionName()!="index" && $this->getRequest()->getActionName()!="filter"): ?>
        if(confirm("<?php echo $this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.') ?>")){
            setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
            return true;
        }
        else {
            obj.value = '<?php echo $this->getStoreId() ?>';
        }
        return false;
    <?php else: ?>
        setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
    <?php endif; ?>
    }
</script>
<?php endif; ?>
