<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     default_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php list($formHtml,$html) = $this->getSearchFormHtml(); ?>
<?php echo $formHtml; ?>
<div id="order-items">
	<?php echo $html; ?>
</div>
<div id="order-errors"></div>
<br/>
<div id="order-search" class="csmarketplace-order-search-items" style="display:none">
	<?php echo $this->getLayout()->createBlock('csmarketplace/adminhtml_vpayments_edit_tab_addorder_search')->setTemplate('csmarketplace/vpayments/edit/tab/addorder/search.phtml')->toHtml(); ?>
</div>