<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="input-box customer-dob">
<?php
    $this->setDateInput('d',
        '<div class="input-box dob-day">
             <input placeholder="'.$this->__('DD').'" type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="form-control input-text validate-custom" ' . $this->getFieldParams() . ' />
             
         </div>'
    );

    $this->setDateInput('m',
        '<div class="input-box dob-month">
             <input placeholder="' . $this->__('MM')  . '" type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="form-control input-text validate-custom" ' . $this->getFieldParams()  . ' />
            
         </div>'
    );

    $this->setDateInput('y',
        '<div class="input-box dob-year">
             <input placeholder="' . $this->__('YYYY')  . '" type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="form-control input-text validate-custom" ' . $this->getFieldParams()  . ' />
             
         </div>'
    );
?>
    <?php echo $this->getSortedDateInputs() ?>
    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div class="validation-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
<style>
#advice-validate-custom-month,#advice-validate-custom-day,#advice-validate-custom-year{
display:none !important;
}
</style>